Repository gii-is-psg2/psg2-2122-g4-42, pull requests merged in 2022-04, with the labels that each got.

#73 Feature/43 donation
  src/main/java/org/springframework/samples/petclinic/cause/Cause.java
  src/main/java/org/springframework/samples/petclinic/cause/CauseService.java
  src/main/java/org/springframework/samples/petclinic/cause/Donation.java
  src/main/java/org/springframework/samples/petclinic/cause/DonationRepository.java
  src/main/resources/db/hsqldb/data.sql
  src/test/java/org/springframework/samples/petclinic/cause/CauseServiceTests.java
Labels: enhancement

#75 Adoptions functionality
  .vscode/launch.json
  src/main/java/org/springframework/samples/petclinic/adoption/Adoption.java
  src/main/java/org/springframework/samples/petclinic/adoption/AdoptionController.java
  src/main/java/org/springframework/samples/petclinic/adoption/AdoptionRepository.java
  src/main/java/org/springframework/samples/petclinic/adoption/AdoptionService.java
  src/main/java/org/springframework/samples/petclinic/adoption/RequestAdoption.java
  src/main/java/org/springframework/samples/petclinic/adoption/RequestAdoptionRepository.java
  src/main/java/org/springframework/samples/petclinic/adoption/RequestAdoptionService.java
  src/main/java/org/springframework/samples/petclinic/adoption/Status.java
  src/main/java/org/springframework/samples/petclinic/configuration/SecurityConfiguration.java
  src/main/java/org/springframework/samples/petclinic/owner/Owner.java
  src/main/java/org/springframework/samples/petclinic/owner/OwnerController.java
  src/main/java/org/springframework/samples/petclinic/owner/OwnerRepository.java
  src/main/java/org/springframework/samples/petclinic/owner/OwnerService.java
  src/main/java/org/springframework/samples/petclinic/pet/Pet.java
  src/main/java/org/springframework/samples/petclinic/pet/PetService.java
  src/main/java/org/springframework/samples/petclinic/user/UserRepository.java
  src/main/java/org/springframework/samples/petclinic/user/UserService.java
  src/main/less/petclinic.less
  src/main/resources/db/hsqldb/data.sql
  src/main/webapp/WEB-INF/jsp/adoptions/adoptionList.jsp
  src/main/webapp/WEB-INF/jsp/adoptions/adoptionRequestList.jsp
  src/main/webapp/WEB-INF/jsp/adoptions/createAdoptionForm.jsp
  src/main/webapp/WEB-INF/jsp/adoptions/createRequestAdoptionForm.jsp
  src/main/webapp/WEB-INF/tags/menu.tag
  src/test/java/org/springframework/samples/petclinic/adoption/AdoptionControllerTests.java
  src/test/java/org/springframework/samples/petclinic/adoption/AdoptionServiceTests.java
  src/test/java/org/springframework/samples/petclinic/adoption/RequestAdoptionServiceTests.java
Labels: enhancement

#76 feat: Create Cause Section
  src/main/java/org/springframework/samples/petclinic/cause/CauseController.java
  src/main/java/org/springframework/samples/petclinic/configuration/SecurityConfiguration.java
  src/main/webapp/WEB-INF/jsp/causes/causeList.jsp
  src/main/webapp/WEB-INF/tags/menu.tag
Labels: enhancement

#77 Add owner to requestAdoptions cards
  src/main/webapp/WEB-INF/jsp/adoptions/adoptionList.jsp
  src/main/webapp/WEB-INF/jsp/adoptions/adoptionRequestList.jsp
Labels: enhancement

#78 feat: create donation form
  src/main/java/org/springframework/samples/petclinic/cause/Cause.java
  src/main/java/org/springframework/samples/petclinic/cause/CauseController.java
  src/main/java/org/springframework/samples/petclinic/cause/CauseService.java
  src/main/java/org/springframework/samples/petclinic/cause/Donation.java
  src/main/java/org/springframework/samples/petclinic/cause/DonationController.java
  src/main/resources/db/hsqldb/data.sql
  src/main/webapp/WEB-INF/jsp/causes/causeList.jsp
  src/main/webapp/WEB-INF/jsp/causes/donationForm.jsp
  src/test/java/org/springframework/samples/petclinic/cause/CauseServiceTests.java
Labels: enhancement

#79 Feature/35 cause details
  src/main/java/org/springframework/samples/petclinic/cause/CauseController.java
  src/main/webapp/WEB-INF/jsp/causes/causeDetails.jsp
  src/main/webapp/WEB-INF/jsp/causes/causeList.jsp
  src/test/java/org/springframework/samples/petclinic/cause/CauseControllerTests.java
Labels: enhancement

#80 Feature/44.1 cause form
  src/main/java/org/springframework/samples/petclinic/cause/CauseController.java
  src/main/java/org/springframework/samples/petclinic/hotel/HotelController.java
  src/main/resources/messages/messages.properties
  src/main/webapp/WEB-INF/jsp/causes/causeList.jsp
  src/main/webapp/WEB-INF/jsp/causes/createCauseForm.jsp
  src/test/java/org/springframework/samples/petclinic/cause/CauseControllerTests.java
Labels: enhancement

#82 Causes functionality
  src/main/java/org/springframework/samples/petclinic/cause/Cause.java
  src/main/java/org/springframework/samples/petclinic/cause/CauseController.java
  src/main/java/org/springframework/samples/petclinic/cause/CauseRepository.java
  src/main/java/org/springframework/samples/petclinic/cause/CauseService.java
  src/main/java/org/springframework/samples/petclinic/cause/Donation.java
  src/main/java/org/springframework/samples/petclinic/cause/DonationController.java
  src/main/java/org/springframework/samples/petclinic/cause/DonationRepository.java
  src/main/java/org/springframework/samples/petclinic/configuration/SecurityConfiguration.java
  src/main/resources/db/hsqldb/data.sql
  src/main/resources/messages/messages.properties
  src/main/webapp/WEB-INF/jsp/causes/causeDetails.jsp
  src/main/webapp/WEB-INF/jsp/causes/causeList.jsp
  src/main/webapp/WEB-INF/jsp/causes/createCauseForm.jsp
  src/main/webapp/WEB-INF/jsp/causes/donationForm.jsp
  src/main/webapp/WEB-INF/tags/menu.tag
  src/test/java/org/springframework/samples/petclinic/cause/CauseControllerTests.java
  src/test/java/org/springframework/samples/petclinic/cause/CauseServiceTests.java
Labels: enhancement

#83 Release 2.0.0
  .vscode/launch.json
  src/main/java/org/springframework/samples/petclinic/adoption/Adoption.java
  src/main/java/org/springframework/samples/petclinic/adoption/AdoptionController.java
  src/main/java/org/springframework/samples/petclinic/adoption/AdoptionRepository.java
  src/main/java/org/springframework/samples/petclinic/adoption/AdoptionService.java
  src/main/java/org/springframework/samples/petclinic/adoption/RequestAdoption.java
  src/main/java/org/springframework/samples/petclinic/adoption/RequestAdoptionRepository.java
  src/main/java/org/springframework/samples/petclinic/adoption/RequestAdoptionService.java
  src/main/java/org/springframework/samples/petclinic/adoption/Status.java
  src/main/java/org/springframework/samples/petclinic/cause/Cause.java
  src/main/java/org/springframework/samples/petclinic/cause/CauseController.java
  src/main/java/org/springframework/samples/petclinic/cause/CauseRepository.java
  src/main/java/org/springframework/samples/petclinic/cause/CauseService.java
  src/main/java/org/springframework/samples/petclinic/cause/Donation.java
  src/main/java/org/springframework/samples/petclinic/cause/DonationController.java
  src/main/java/org/springframework/samples/petclinic/cause/DonationRepository.java
  src/main/java/org/springframework/samples/petclinic/configuration/SecurityConfiguration.java
  src/main/java/org/springframework/samples/petclinic/hotel/HotelController.java
  src/main/java/org/springframework/samples/petclinic/owner/Owner.java
  src/main/java/org/springframework/samples/petclinic/owner/OwnerController.java
  src/main/java/org/springframework/samples/petclinic/owner/OwnerRepository.java
  src/main/java/org/springframework/samples/petclinic/owner/OwnerService.java
  src/main/java/org/springframework/samples/petclinic/pet/Pet.java
  src/main/java/org/springframework/samples/petclinic/pet/PetService.java
  src/main/java/org/springframework/samples/petclinic/user/UserRepository.java
  src/main/java/org/springframework/samples/petclinic/user/UserService.java
  src/main/less/petclinic.less
  src/main/resources/db/hsqldb/data.sql
  src/main/resources/messages/messages.properties
  src/main/webapp/WEB-INF/jsp/adoptions/adoptionList.jsp
  src/main/webapp/WEB-INF/jsp/adoptions/adoptionRequestList.jsp
  src/main/webapp/WEB-INF/jsp/adoptions/createAdoptionForm.jsp
  src/main/webapp/WEB-INF/jsp/adoptions/createRequestAdoptionForm.jsp
  src/main/webapp/WEB-INF/jsp/causes/causeDetails.jsp
  src/main/webapp/WEB-INF/jsp/causes/causeList.jsp
  src/main/webapp/WEB-INF/jsp/causes/createCauseForm.jsp
  src/main/webapp/WEB-INF/jsp/causes/donationForm.jsp
  src/main/webapp/WEB-INF/tags/menu.tag
  src/test/java/org/springframework/samples/petclinic/adoption/AdoptionControllerTests.java
  src/test/java/org/springframework/samples/petclinic/adoption/AdoptionServiceTests.java
  src/test/java/org/springframework/samples/petclinic/adoption/RequestAdoptionServiceTests.java
  src/test/java/org/springframework/samples/petclinic/cause/CauseControllerTests.java
  src/test/java/org/springframework/samples/petclinic/cause/CauseServiceTests.java
  src/test/java/org/springframework/samples/petclinic/hotel/HotelControllerTests.java
Labels: enhancement

#84 Release 2.0.0
  src/main/java/org/springframework/samples/petclinic/cause/DonationController.java
  src/main/java/org/springframework/samples/petclinic/hotel/HotelController.java
  src/main/resources/messages/messages.properties
  src/test/java/org/springframework/samples/petclinic/hotel/HotelControllerTests.java
Labels: enhancement

#86 Hotfix 2.0.1
  src/main/java/org/springframework/samples/petclinic/adoption/AdoptionController.java
  src/main/java/org/springframework/samples/petclinic/adoption/AdoptionService.java
  src/main/java/org/springframework/samples/petclinic/cause/CauseController.java
  src/main/java/org/springframework/samples/petclinic/cause/CauseService.java
  src/main/java/org/springframework/samples/petclinic/cause/DonationController.java
  src/main/java/org/springframework/samples/petclinic/hotel/HotelController.java
  src/main/java/org/springframework/samples/petclinic/vet/VetController.java
Labels: bug

#85 Metrics
  nikoniko.md
Labels: documentation

#87 Hotfix 2.0.1
  src/main/java/org/springframework/samples/petclinic/adoption/AdoptionController.java
  src/main/java/org/springframework/samples/petclinic/adoption/AdoptionService.java
  src/main/java/org/springframework/samples/petclinic/cause/CauseController.java
  src/main/java/org/springframework/samples/petclinic/cause/CauseService.java
  src/main/java/org/springframework/samples/petclinic/cause/DonationController.java
  src/main/java/org/springframework/samples/petclinic/hotel/HotelController.java
  src/main/java/org/springframework/samples/petclinic/vet/VetController.java
Labels: bug

#88 Release 2.1.0
  nikoniko.md
Labels: documentation
